### ISSUE TITLE
Feature Request: Individual Heater Timeouts

### ISSUE THREAD

**Issue by ghost** [tjjfvi/OctoPrint-BetterHeaterTimeout#1]
Would it be possible to implement individual timeouts per heater? I'd like to put a shorter timeout for the extruder to avoid filament degradation but a longer one for the bed so I can use it to preheat the enclosure and just use the timeout as a failsafe in case I forget turning it off.

**Comment by tjjfvi** [comment]
@thubot: Yes it would be possible. I am working on it and will let you know when it is implemented.

**Comment by tjjfvi** [comment]
@thubot: I have pushed a test onto the `beta` branch; could you confirm it works?

To install, use this URL:

```
https://github.com/tjjfvi/OctoPrint-BetterHeaterTimeout/archive/beta.zip
```

**Comment by ghost** [comment]
You're awesome. I'll try it in the next days and report back.

**Comment by ghost** [comment]
I tested it for a bit and it seems to work great so far, it's really useful for me.

Thanks a lot.

**Comment by tjjfvi** [comment]
Merged & released; closing!
