### ISSUE TITLE
Feature request : Custome GCode on Timeout

### ISSUE THREAD

**Issue by towlerg** [tjjfvi/OctoPrint-BetterHeaterTimeout#16]
Hi, I see there are a couple of requests about timeout. I was tempted to add mine to one of those but I can't seem to find a good fit. If this is covered bu one of those, then please close this.

I find that when I've almost finish in CAD, I go to OP and hit preheat. But then, as always I underestimate how long it'll take before slicer ready and Preheat times out. I understand that I can change the timeout but I can't find a period that suits all cases. Would it be possible to add the option of custom GCode on timeout (so I can do something to get my attention).

Thanks in advance, George

**Comment by tjjfvi** [comment]
You can already do this with [before/after gcode](https://github.com/tjjfvi/OctoPrint-BetterHeaterTimeout#beforeafter-gcode); I, for example, have mine set up to beep and display a message when it times out.

**Comment by towlerg** [comment]
I must admit I was alittle confused. I put GCode for a double beep in After and I thought that went off when bed and nozzle were upto temp? Perhaps the timeout was too short and confused me. Which GCode get actioned when the plugin timesout?

**Comment by tjjfvi** [comment]
The before/after gcode runs before/after it shuts down the heater. Are you sure you added the correct gcode / that your printer supports beep gcode? Try adding
```
M117 $heater timed out
```
I believe most printers support `M117`.

**Comment by towlerg** [comment]
I think the problem is dim user syndrome, nothing wrong with the printer. For no apparent reason I assumed that before meant before the heaters were turned on and after meant after the heaters reached temp, which of course makes no sense whatsoever.

So any message I print in before will be immediately overwritten by an after message?

I'm curious, under what circumstances do you need custom GCode before and after heater switch off?

**Comment by tjjfvi** [comment]
> So any message I print in before will be immediately overwritten by an after message?

Yup.

> I'm curious, under what circumstances do you need custom GCode before and after heater switch off?

🤷
