### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by jtkdaddy** [tjjfvi/OctoPrint-BetterHeaterTimeout#7]
This plugin fails the Python 3 compatibility check performed by this plugin:
https://github.com/jneilliii/OctoPrint-Python3PluginCompatibilityCheck

**Comment by Brebinator** [comment]
Ocotoprint will no longer support previous versions of python in the near future, it would be awesome if this plugin could get updated to be compatible with python 3.6.

**Comment by OldCurmudgeon3DP** [comment]
I'll raise a 3rd hand for updating the compatibility. I hear that "forcing" compatibility in the cfg can work as a band-aid, but has a good chance of breaking Octoprint in the process.

**Comment by mild-lemon** [comment]
#metoo  
Please update plugin to be compatible with python3.
